### ISSUE TITLE
Game are not named correctly when injecting

### ISSUE THREAD

**Issue by mariogamer2** [vickdu31/Haxchi_Installer#3]
Hy,

I say that you inject directly the rom like "brainage.zip" and with the rome name "brainage.nds".

This "brick" the game,because the rom need to be named in another way,for exemple:

brain age USA -> rom.zip -> WUP-N-DAAE.nds

**Comment by vickdu31** [comment]
I can assure you it is the correct name. Please check fix94 haxchi files.
Read the troubleshoot if you have problems or contact me

**Comment by mariogamer2** [comment]
I do not personally have problem with this...

And nope it's not the correct name. Just dl a rom from any game compare the name of the nds and you will see...

**Comment by vickdu31** [comment]
Did you check oroginal haxchi files from fix94 ?
It have been working like this since the begening.
