### ISSUE TITLE
Not restarting after install

### ISSUE THREAD

**Issue by twig** [vickdu31/Haxchi_Installer#6]
Python 2.7

> Press enter to exit program...
> Exception struct.error: 'unpack requires a string argument of length 4' in <bound method wupclient.__del__ of <wupclient.wupclient instance at 0x028399B8>> ignored

**Comment by twig** [comment]
Also, it still runs the original NDS rom instead of the hack.

**Comment by vickdu31** [comment]
Could you explain the problem a bit better ? :)

**Comment by vickdu31** [comment]
If you open it from CMD, you get an error at the exit because I didnt find a proper way to kill wupclient. But if you open it from python (double click) then this error message also kill python window so people don't notice. Its totally harmless

**Comment by twig** [comment]
ahh yes I ran it via cmd using "python haxchi...py"

**Comment by twig** [comment]
I'm on mobile atm but can you link me to the file where it stops the wupclient?

**Comment by twig** [comment]
never mind, it's only one file. I'll check it out when I can
